name: super-pharm clone
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, v0.1, v0.2, v0.3 ]
jobs:
  build:
    env:
      CI: true
      MONGO_URI_TEST: mongodb://localhost/super-pharm-clone
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run start